# Generated by Django 4.1 on 2022-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hero_name", models.CharField(max_length=500)),
                ("quirk", models.CharField(max_length=100)),
                ("dob", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
